name: memomemo
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  google_fonts: ^6.3.2
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  shared_preferences: ^2.5.3
  uuid: ^4.5.2
  url_launcher: ^6.3.2
  flutter_riverpod: ^3.0.3
  firebase_core: ^4.2.1
  firebase_crashlytics: ^5.0.5
  
dev_dependencies:
  json_serializable: ^6.7.1
  build_runner: ^2.4.8
  freezed: ^2.3.2
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/